name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: quay.io/rh_ee_rsaini/bodhi-scraper
    steps:
      - name: Where am i
        run: pwd
      - name: Run Script
        run: python3 /usr/bodhi_scraper/Bodhiscraper.py
